# Generated by Django 5.2.16 on 2026-08-02 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DictMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True, verbose_name='词库标识')),
                ('name', models.CharField(max_length=100, verbose_name='词库名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='词条数')),
                ('difficulty', models.CharField(blank=True, default='', max_length=32)),
                ('category', models.CharField(blank=True, default='', max_length=64)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(blank=True, default='', max_length=200)),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '词库',
                'verbose_name_plural': '词库',
            },
        ),
        migrations.CreateModel(
            name='ExampleCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('word', models.CharField(max_length=100)),
                ('with_translation', models.BooleanField()),
                ('style', models.CharField(max_length=20)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '例句缓存',
                'verbose_name_plural': '例句缓存',
            },
        ),
        migrations.CreateModel(
            name='ProgressBlob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress_blob', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '学习进度',
                'verbose_name_plural': '学习进度',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, default='', max_length=50, verbose_name='昵称')),
                ('bio', models.CharField(blank=True, default='', max_length=200, verbose_name='简介')),
                ('daily_goal', models.PositiveIntegerField(default=20, verbose_name='每日目标')),
                ('avatar_color', models.CharField(blank=True, default='emerald', max_length=20)),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='设置')),
                ('last_active_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
            },
        ),
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('words_new', models.PositiveIntegerField(default=0)),
                ('words_reviewed', models.PositiveIntegerField(default=0)),
                ('words_wrong', models.PositiveIntegerField(default=0)),
                ('seconds', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '每日活动',
                'verbose_name_plural': '每日活动',
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wid', models.PositiveIntegerField(verbose_name='词内序号')),
                ('word', models.CharField(max_length=200)),
                ('word_lower', models.CharField(db_index=True, max_length=200)),
                ('meaning', models.TextField(blank=True, default='')),
                ('alt', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('subcategory', models.CharField(blank=True, max_length=100, null=True)),
                ('freq', models.IntegerField(default=0)),
                ('ipa', models.CharField(blank=True, max_length=200, null=True)),
                ('dict_meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='api.dictmeta')),
            ],
            options={
                'verbose_name': '单词',
                'verbose_name_plural': '单词',
                'indexes': [models.Index(fields=['dict_meta', 'word_lower'], name='api_word_dict_me_0a948a_idx'), models.Index(fields=['dict_meta', 'category'], name='api_word_dict_me_3e8b4d_idx'), models.Index(fields=['dict_meta', 'freq'], name='api_word_dict_me_13aba9_idx')],
                'unique_together': {('dict_meta', 'word_lower')},
            },
        ),
        migrations.CreateModel(
            name='WordNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dict_key', models.CharField(default='kaoyan', max_length=64)),
                ('word', models.CharField(max_length=200)),
                ('note', models.TextField(blank=True, default='')),
                ('syllable_notes', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '单词笔记',
                'verbose_name_plural': '单词笔记',
                'unique_together': {('user', 'dict_key', 'word')},
            },
        ),
    ]
